spring.application.name=Jwt-Auth-Spring-Boot

spring.datasource.url=jdbc:postgresql://localhost:5432/project1
spring.datasource.username=postgres
spring.datasource.password=abc123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
